//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_appointment> tb_appointment { get; set; }
        public virtual DbSet<tb_clinicalrecord> tb_clinicalrecord { get; set; }
        public virtual DbSet<tb_employee> tb_employee { get; set; }
        public virtual DbSet<tb_examination> tb_examination { get; set; }
        public virtual DbSet<tb_examination_act> tb_examination_act { get; set; }
        public virtual DbSet<tb_examinetype> tb_examinetype { get; set; }
        public virtual DbSet<tb_medicine> tb_medicine { get; set; }
        public virtual DbSet<tb_paramact> tb_paramact { get; set; }
        public virtual DbSet<tb_paramprescription> tb_paramprescription { get; set; }
        public virtual DbSet<tb_paramprescription_medicine> tb_paramprescription_medicine { get; set; }
        public virtual DbSet<tb_patient> tb_patient { get; set; }
        public virtual DbSet<tb_patient_clinicalrecord> tb_patient_clinicalrecord { get; set; }
        public virtual DbSet<tb_prescription> tb_prescription { get; set; }
        public virtual DbSet<tb_prescription_detail> tb_prescription_detail { get; set; }
        public virtual DbSet<tb_profession> tb_profession { get; set; }
        public virtual DbSet<tb_relative_paramact> tb_relative_paramact { get; set; }
    }
}
