//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_appointment
    {
        public int AppointmentID { get; set; }
        public string DoctorID { get; set; }
        public string PatientID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Content { get; set; }
        public string State { get; set; }
    
        public virtual tb_employee tb_employee { get; set; }
    }
}
