//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_employee
    {
        public tb_employee()
        {
            this.tb_appointment = new HashSet<tb_appointment>();
            this.tb_examination = new HashSet<tb_examination>();
            this.tb_examination_act = new HashSet<tb_examination_act>();
            this.tb_paramprescription = new HashSet<tb_paramprescription>();
            this.tb_prescription = new HashSet<tb_prescription>();
        }
    
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public string NativeCountry { get; set; }
        public string Address { get; set; }
        public string IdentityCard { get; set; }
        public string Tel { get; set; }
        public string MobilePhone { get; set; }
        public System.DateTime DateJoin { get; set; }
        public string Email { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<tb_appointment> tb_appointment { get; set; }
        public virtual ICollection<tb_examination> tb_examination { get; set; }
        public virtual ICollection<tb_examination_act> tb_examination_act { get; set; }
        public virtual ICollection<tb_paramprescription> tb_paramprescription { get; set; }
        public virtual ICollection<tb_prescription> tb_prescription { get; set; }
    }
}
