//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_examination
    {
        public tb_examination()
        {
            this.tb_examination_act = new HashSet<tb_examination_act>();
            this.tb_prescription = new HashSet<tb_prescription>();
        }
    
        public int ExaminationID { get; set; }
        public string PatientID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ExamineTypeID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string PersonSettingID { get; set; }
        public int IsExamine { get; set; }
    
        public virtual tb_employee tb_employee { get; set; }
        public virtual tb_examinetype tb_examinetype { get; set; }
        public virtual ICollection<tb_examination_act> tb_examination_act { get; set; }
        public virtual ICollection<tb_prescription> tb_prescription { get; set; }
    }
}
