//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_examination_act
    {
        public int Examination_ActID { get; set; }
        public int ExaminationID { get; set; }
        public Nullable<int> ParamActID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string Description { get; set; }
        public string State { get; set; }
        public string toothProperty { get; set; }
        public string positionProperty { get; set; }
        public Nullable<int> IsCommonAct { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string DoctorID { get; set; }
        public Nullable<int> numberact { get; set; }
    
        public virtual tb_employee tb_employee { get; set; }
        public virtual tb_examination tb_examination { get; set; }
        public virtual tb_paramact tb_paramact { get; set; }
    }
}
