//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_medicine
    {
        public tb_medicine()
        {
            this.tb_paramprescription_medicine = new HashSet<tb_paramprescription_medicine>();
            this.tb_prescription_detail = new HashSet<tb_prescription_detail>();
        }
    
        public int MedicineID { get; set; }
        public string MedicineCode { get; set; }
        public string MedicineName { get; set; }
        public string Country { get; set; }
        public Nullable<int> ServiceLife { get; set; }
        public string UnitLife { get; set; }
        public string UsesOfMedicine { get; set; }
        public string UnitType { get; set; }
    
        public virtual ICollection<tb_paramprescription_medicine> tb_paramprescription_medicine { get; set; }
        public virtual ICollection<tb_prescription_detail> tb_prescription_detail { get; set; }
    }
}
