//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_profession
    {
        public tb_profession()
        {
            this.tb_patient = new HashSet<tb_patient>();
        }
    
        public int ProfessionID { get; set; }
        public string ProfessionName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tb_patient> tb_patient { get; set; }
    }
}
