//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_paramact
    {
        public tb_paramact()
        {
            this.tb_examination_act = new HashSet<tb_examination_act>();
            this.tb_examinetype = new HashSet<tb_examinetype>();
        }
    
        public int ParamActID { get; set; }
        public string ParamActName { get; set; }
        public int TimeOfExecution { get; set; }
        public string Description { get; set; }
        public Nullable<int> relative_paramact_id { get; set; }
    
        public virtual ICollection<tb_examination_act> tb_examination_act { get; set; }
        public virtual tb_relative_paramact tb_relative_paramact { get; set; }
        public virtual ICollection<tb_examinetype> tb_examinetype { get; set; }
    }
}
