//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_patient
    {
        public int ID { get; set; }
        public string PatientID { get; set; }
        public string NickName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Marital { get; set; }
        public string Gender { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public byte[] Picture { get; set; }
        public string Note { get; set; }
    
        public virtual tb_profession tb_profession { get; set; }
    }
}
