//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagerPartient.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_relative_paramact
    {
        public tb_relative_paramact()
        {
            this.tb_paramact = new HashSet<tb_paramact>();
        }
    
        public int relative_paramact_id { get; set; }
        public string relative_paramact_name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tb_paramact> tb_paramact { get; set; }
    }
}
