//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageSoftware.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_exercise
    {
        public tb_exercise()
        {
            this.tb_person_exercise = new HashSet<tb_person_exercise>();
        }
    
        public int ExerciseID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<int> ConfigID_Default { get; set; }
    
        public virtual tb_config_practice tb_config_practice { get; set; }
        public virtual ICollection<tb_person_exercise> tb_person_exercise { get; set; }
    }
}
