//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageSoftware.ModelManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_person
    {
        public tb_person()
        {
            this.tb_person_exercise = new HashSet<tb_person_exercise>();
        }
    
        public int ID { get; set; }
        public string PersonID { get; set; }
        public string NickName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Marital { get; set; }
        public string Gender { get; set; }
        public Nullable<int> ProfessionID { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public byte[] Picture { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<tb_person_exercise> tb_person_exercise { get; set; }
    }
}
